import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Accessible Interactions</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="main">
        <h1>Accessible Interactions</h1>
        <nav className="mainNav">
          <ul>
            <li>
              <Link href="/accname">Accessible Names</Link>
            </li>
            <li>
              <Link href="/addComponents">Adding Components</Link>
            </li>
            <li>
              <Link href="/changePage">Changing Page</Link>
            </li>
            <li>
              <Link href="/disclosures">Disclosures</Link>
            </li>
            <li>
              <Link href="/errorMessages">Error Messages</Link>
            </li>
            <li>
              <Link href="/modals">Modals</Link>
            </li>
            <li>
              <Link href="/removeComponent">
                Removing or replacing components
              </Link>
            </li>
          </ul>
        </nav>
      </main>
    </>
  );
}
